Introduce com.android.documentsui.flags.redirect_get_content
This flag will be used to guard a new activity that will decide
whether to redirect a GET_CONTENT request to Photopicker or not.

The flags_packages are required otherwise it fails with an error:

  error: attribute 'android:featureFlag' has flag
  'com.android.documentsui.flags.redirect_get_content'
  not found in flags from --feature_flags parameter

Bug: 377771195
Test: EXEMPT adding a flag
Flag: com.android.documentsui.flags.redirect_get_content
Change-Id: I4ab2100c8e1b9bd4cb237acec334cb0aff14cb19